- type: job
  id: Pretor
  name: job-name-pretor
  description: job-description-pretor
  playTimeTracker: JobPretor
  requirements:
    - !type:RoleTimeRequirement
      role: JobKseno
      time: 36000 # 10 hrs
  canBeAntag: false
  icon: "JobIconPretor"
  supervisors: job-supervisors-quinn
  jobEntity: MobPraetorianXeno
