- type: job
  id: Runi
  name: job-name-runi
  description: job-description-runi
  playTimeTracker: JobRuni
  requirements:
    - !type:RoleTimeRequirement
      role: JobKseno
      time: 36000 # 10 hrs
  canBeAntag: false
  icon: "JobIconRuni"
  supervisors: job-supervisors-quinn
  jobEntity: MobRounyXeno
