- type: job
  id: CharlieEngineer
  name: job-name-charlie-engineer
  description: job-description-charlieengineer
  playTimeTracker: JobCharlieEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 10800 # 3 hrs
  startingGear: CharlieEngineerGear
  icon: "JobIconCharlieEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadCharlie
    - Engineering
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: CharlieEngineer

- type: startingGear
  id: CharlieEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_eng
    id: CEngineerIDCard
    ears: ClothingHeadsetMarineCharlie
    pocket1: EmergencyMedipen
