- type: job
  id: CharlieSpecialist
  name: job-name-charlie-specialist
  description: job-description-charliespecialist
  playTimeTracker: JobCharlieSpecialist
  requirements:
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 18000 # 5 hrs
  startingGear: CharlieSpecialistGear
  icon: "JobIconCharlieSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadCharlie
    - SquadSpecialist
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: CharlieSpecialist

- type: startingGear
  id: CharlieSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_spec
    id: CSpecialistsIDCard
    ears: ClothingHeadsetMarineCharlie
