- type: job
  id: AlfaEngineer
  name: job-name-alfa-engineer
  description: job-description-alfaengineer
  playTimeTracker: JobAlfaEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 3600 # 1 hrs
  startingGear: AlfaEngineerGear
  icon: "JobIconAlfaEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadAlpha
    - Engineering
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: AlfaEngineer

- type: startingGear
  id: AlfaEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_eng
    id: AEngineerIDCard
    ears: ClothingHeadsetMarineAlfa
