- type: job
  id: FieldCommander
  name: job-name-fieldcommander
  description: job-supervisors-staff-officer
  playTimeTracker: JobFieldCommander
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: FieldCommanderGear
  icon: "JobIconFieldCommander"
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  accessGroups:
    - HeadOperations

- type: startingGear
  id: FieldCommanderGear
  equipment:
    head: ClothingHeadHatBeretFieldCommander
    outerClothing: ClothingOuterArmorFieldCommander
    gloves: ClothingHandsGlovesMarine
    jumpsuit: ClothingUniformJumpsuitFieldCommander
    eyes: ClothingEyesGlassesRPG
    id: FieldCommanderIDCard
    ears: ClothingHeadsetMarineCommands
    belt: ClothingBeltSecurityFilled
    shoes: ClothingShoesBootsMarine
    pocket2: ClothingMaskGasFieldCommander
