- type: job
  id: ChiefShipsEngineer
  name: job-name-chiefshipsengineer
  description: job-supervisors-staff-officer
  playTimeTracker: JobChiefShipsEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 36000 # 10 hrs
  startingGear: ChiefShipsEngineerGear
  icon: "JobIconChiefShipsEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance
    - Atmospherics
    - Engineering
    - Command
    - ChiefEngineer

- type: startingGear
  id: ChiefShipsEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
    id: ChiefShipsEngineerIDCard
