- type: job
  id: CharlieCommander
  name: job-name-charlie-commander
  description: job-description-charliecommander
  playTimeTracker: JobCharlieCommander
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 36000 # 10 hrs
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 108000 # 30 hrs
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 36000 # 10 hrs
  startingGear: CharlieCommanderGear
  icon: "JobIconCharlieCommander"
  supervisors: job-supervisors-field-commander
  canBeAntag: false
  access:
    - SquadCharlie
    - SquadLeader
    - SquadSpecialist
    - Engineering
    - Command
    - Medical

- type: startingGear
  id: CharlieCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_leader
    id: CCommanderIDCard
    ears: ClothingHeadsetMarineCharlieLeader
