- type: job
  id: CharlieSpecialist
  name: job-name-charlie-specialist
  description: job-description-charliespecialist
  playTimeTracker: JobCharlieSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 18000 # 5 hrs
  startingGear: CharlieSpecialistGear
  icon: "JobIconCharlieSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadCharlie
    - SquadSpecialist

- type: startingGear
  id: CharlieSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_spec
    id: CSpecialistsIDCard
    ears: ClothingHeadsetMarineCharlie
