- type: job
  id: CharlieMedic
  name: job-name-charlie-medic
  description: job-description-charliemedic
  playTimeTracker: JobCharlieMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 18000 # 5 hrs
  startingGear: CharlieMedicGear
  icon: "JobIconCharlieMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadCharlieMedic

- type: startingGear
  id: CharlieMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_med
    id: CMedicIDCard
    ears: ClothingHeadsetMarineCharlie
