- type: job
  id: CharlieSpecialist
  name: job-name-charlie-specialist
  description: job-description-charliespecialist
  playTimeTracker: JobCharlieSpecialist
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: CharlieSpecialistGear
  icon: "JobIconCharlieSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadCharlie
    - SquadSpecialist

- type: startingGear
  id: CharlieSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_spec
    id: CSpecialistsIDCard
    ears: ClothingHeadsetMarineCharlie