- type: job
  id: CharlieMarine
  name: job-name-charlie-marine
  description: job-description-charlieamarine
  playTimeTracker: JobCharlieMarine
  startingGear: CharlieMarineGear
  icon: "JobIconCharlieMarine"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - TGMSC

- type: startingGear
  id: CharlieMarineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_mar
    id: CRiflemanIDCard
    ears: ClothingHeadsetMarineCharlie
