- type: job
  id: CharlieMedic
  name: job-name-charlie-medic
  description: job-description-charliemedic
  playTimeTracker: JobCharlieMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: CharlieMedicGear
  icon: "JobIconCharlieMedic"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - TGMSCM

- type: startingGear
  id: CharlieMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitcharlie_med
    id: CMedicIDCard
    ears: ClothingHeadsetMarineCharlie
