- type: job
  id: DeltaMedic
  name: job-name-delta-medic
  description: job-description-deltamedic
  playTimeTracker: JobDeltaMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 3600 # 1 hrs
  startingGear: DeltaMedicGear
  icon: "JobIconDeltaMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadDeltaMedic
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: DeltaMedic

- type: startingGear
  id: DeltaMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitdelta_med
    id: DMedicIDCard
    ears: ClothingHeadsetMarineDelta
