- type: job
  id: DeltaSpecialist
  name: job-name-delta-specialist
  description: job-description-deltaspecialist
  playTimeTracker: JobDeltaSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 54000 # 15 hrs
  startingGear: DeltaSpecialistGear
  icon: "JobIconDeltaSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadDelta
    - SquadSpecialist
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: DeltaSpecialist

- type: startingGear
  id: DeltaSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitdelta_spec
    id: DSpecialistsIDCard
    ears: ClothingHeadsetMarineDelta
