- type: job
  id: DeltaCommander
  name: job-name-delta-commander
  description: job-description-deltacommander
  playTimeTracker: JobDeltaCommander
  requirements:
    - !type:DepartmentTimeRequirement
      department: EngineersGarrison
      time: 10800 # 3 hrs
    - !type:DepartmentTimeRequirement
      department: SpecialistsGarrison
      time: 10800 # 3 hrs
    - !type:DepartmentTimeRequirement
      department: MedicsGarrison
      time: 10800 # 3 hrs
  startingGear: DeltaCommanderGear
  icon: "JobIconDeltaCommander"
  supervisors: job-supervisors-field-commander
  canBeAntag: false
  access:
    - SquadDelta
    - SquadLeader
    - SquadSpecialist
    - Engineering
    - Command
    - Medical
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: DeltaCommander

- type: startingGear
  id: DeltaCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitdelta_leader
    id: DCommanderIDCard
    ears: ClothingHeadsetMarineDeltaLeader
