- type: job
  id: DeltaMarine
  name: job-name-delta-marine
  description: job-description-deltamarine
  playTimeTracker: JobDeltaMarine
  requirements:
    - !type:DepartmentTimeRequirement
      department: DeltaGarrison
      time: 0
  startingGear: DeltaMarineGear
  icon: "JobIconDeltaMarine"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - TGMSD

- type: startingGear
  id: DeltaMarineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitdelta_mar
    id: DRiflemanIDCard
    ears: ClothingHeadsetMarineDelta
