- type: job
  id: DeltaEngineer
  name: job-name-delta-engineer
  description: job-description-deltaengineer
  playTimeTracker: JobDeltaEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: DeltaGarrison
      time: 0
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: DeltaEngineerGear
  icon: "JobIconDeltaEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - TGMSDE

- type: startingGear
  id: DeltaEngineerGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: DEngineerIDCard
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
