- type: job
  id: DeltaCommander
  name: job-name-delta-commander
  description: job-description-deltacommander
  playTimeTracker: JobDeltaCommander
  requirements:
    - !type:DepartmentTimeRequirement
      department: SpecialistsGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: MedicsGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: EngineersGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 0
  startingGear: DeltaCommanderGear
  icon: "JobIconDeltaCommander"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - TGMSDSL

- type: startingGear
  id: DeltaCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitdelta_leader
    id: DCommanderIDCard
    ears: ClothingHeadsetMarineDeltaLeader
