- type: job
  id: AlfaCommander
  name: job-name-alfa-commander
  description: job-description-alfacommander
  playTimeTracker: JobAlfaCommander
  requirements:
    - !type:DepartmentTimeRequirement
      department: SpecialistsGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: MedicsGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: EngineersGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 7200
  startingGear: AlfaCommanderGear
  icon: "JobIconAlfaCommander"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - TGMSASL

- type: startingGear
  id: AlfaCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_leader
    id: ACommanderIDCard
    ears: ClothingHeadsetMarineAlfaLeader