- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: Truncheon
  result: Truncheon
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  completetime: 8
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  completetime: 5
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  completetime: 5
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  completetime: 5
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  completetime: 5
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: ShellShotgunPractice
  result: ShellShotgunPractice
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: MagazineBoxPistolPractice
  result: MagazineBoxPistolPractice
  completetime: 5
  materials:
    Plastic: 600

- type: latheRecipe
  id: MagazineBoxMagnumPractice
  result: MagazineBoxMagnumPractice
  completetime: 5
  materials:
    Plastic: 1200

- type: latheRecipe
  id: MagazineBoxLightRiflePractice
  result: MagazineBoxLightRiflePractice
  completetime: 5
  materials:
    Plastic: 1000

- type: latheRecipe
  id: MagazineBoxRiflePractice
  result: MagazineBoxRiflePractice
  completetime: 5
  materials:
    Plastic: 900

- type: latheRecipe
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  completetime: 12
  materials:
    Steel: 2000
    Glass: 400
    Plastic: 500

- type: latheRecipe
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  completetime: 10
  materials:
    Steel: 1900
    Glass: 500
    Plastic: 400

- type: latheRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  id: MagazineRifleM41A
  result: MagazineRifleM41A
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: MagazineRifleM4RA
  result: MagazineRifleM4RA
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: MagazinePistolAramatM5Y3
  result: MagazinePistolAramatM5Y3
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: MagazinePistol88M4
  result: MagazinePistol88M4
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: MagazineRifleM39
  result: MagazineRifleM39
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: Magazine10x24mm
  result: Magazine10x24mm
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: SpeedLoaderMagnumVP-60x2
  result: SpeedLoaderMagnumVP-60x2
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: SpeedLoaderLightRifle
  result: SpeedLoaderLightRifle
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: SpeedLoaderMosin
  result: SpeedLoaderMosin
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: SpeedLoader9mm
  result: SpeedLoader9mm
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: SpeedLoaderMagnum357
  result: SpeedLoaderMagnum357
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: Magazine9mm
  result: Magazine9mm
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: MagazinePP
  result: MagazinePP
  completetime: 2
  materials:
    Steel: 20
    Plastic: 20

- type: latheRecipe
  id: Box10x24mm
  result: Box10x24mm
  completetime: 5
  materials:
    Plastic: 1200
    Steel: 100

- type: latheRecipe
  id: Magazine10x26mm
  result: Magazine10x26mm
  completetime: 5
  materials:
    Plastic: 1200
    Steel: 100

- type: latheRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  completetime: 5
  materials:
    Plastic: 1200
    Steel: 100

- type: latheRecipe
  id: Box9mm
  result: Box9mm
  completetime: 5
  materials:
    Plastic: 1200
    Steel: 100

- type: latheRecipe
  id: MagazineBox357
  result: MagazineBox357
  completetime: 5
  materials:
    Plastic: 1200
    Steel: 100

- type: latheRecipe
  id: ExGrenade
  result: ExGrenade
  completetime: 2
  materials:
    Steel: 100
    Plastic: 100
    Glass: 50
    Plasma: 50
    Silver: 50

- type: latheRecipe
  id: C4
  result: C4
  completetime: 4
  materials:
    Steel: 100
    Plastic: 100
    Glass: 50
    Plasma: 50
    Silver: 50

- type: latheRecipe
  id: MarineCASFlareBomb
  result: MarineCASFlareBomb
  completetime: 10
  materials:
    Steel: 100
    Plastic: 100
    Glass: 50

- type: latheRecipe
  id: MarineCASClusterBomb
  result: MarineCASClusterBomb
  completetime: 10
  materials:
    Steel: 100
    Glass: 50
    Plasma: 50

- type: latheRecipe
  id: MagazineShotgunAFG-12
  result: MagazineShotgunAFG-12
  completetime: 10
  materials:
    Steel: 100
    Plastic: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: FuelTankFlamethrower
  result: FuelTankFlamethrower
  completetime: 10
  materials:
    Steel: 100
    Plastic: 100
    Glass: 100
    Plasma: 1000

- type: latheRecipe
  id: MagazineRifleXM43E
  result: MagazineRifleXM43E
  completetime: 10
  materials:
    Steel: 100
    Plastic: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: MagazineLightRifleBox
  result: MagazineLightRifleBox
  completetime: 10
  materials:
    Steel: 100
    Plastic: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: BoxShotgunLMG
  result: BoxShotgunLMG
  completetime: 10
  materials:
    Steel: 100
    Plastic: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  completetime: 8
  materials:
    Steel: 900
    Glass: 900
    Plasma: 300

- type: latheRecipe
  id: WeaponAntiqueLaser
  result: WeaponAntiqueLaser
  completetime: 10
  materials:
    Steel: 1000
    Glass: 1000
    Plasma: 100
    Gold: 100
