- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200
    
- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: ShellShotgunPractice
  result: ShellShotgunPractice
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: MagazineBoxPistolPractice
  result: MagazineBoxPistolPractice
  completetime: 5
  materials:
    Plastic: 600

- type: latheRecipe
  id: MagazineBoxMagnumPractice
  result: MagazineBoxMagnumPractice
  completetime: 5
  materials:
    Plastic: 1200

- type: latheRecipe
  id: MagazineBoxLightRiflePractice
  result: MagazineBoxLightRiflePractice
  completetime: 5
  materials:
    Plastic: 1000

- type: latheRecipe
  id: MagazineBoxRiflePractice
  result: MagazineBoxRiflePractice
  completetime: 5
  materials:
    Plastic: 900

- type: latheRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200
