- type: job
  id: Rigger
  name: job-name-rigger
  description: job-description-rigger
  playTimeTracker: JobRigger
  startingGear: RiggerGear
  icon: "JobIconRigger"
  supervisors: job-supervisors-supply-officer
  canBeAntag: false
  access:
    - Cargo
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: Rigger

- type: startingGear
  id: RiggerGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    id: RiggerIDCard
