- type: job
  id: BravoSpecialist
  name: job-name-bravo-specialist
  description: job-description-bravospecialist
  playTimeTracker: JobBravoSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 54000 # 15 hrs
  startingGear: BravoSpecialistGear
  icon: "JobIconBravoSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadBravo
    - SquadSpecialist
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: BravoSpecialist

- type: startingGear
  id: BravoSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitbravo_spec
    id: BSpecialistsIDCard
    ears: ClothingHeadsetSpecBravo
    pocket1: EmergencyMedipen
