- type: job
  id: BravoMarine
  name: job-name-bravo-marine
  description: job-description-bravomarine
  playTimeTracker: JobBravoMarine
  startingGear: BravoMarineGear
  icon: "JobIconBravoMarine"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadBravo
    - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: BravoMarine

- type: startingGear
  id: BravoMarineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitbravo_mar
    id: BRiflemanIDCard
    ears: ClothingHeadsetMarineBravo
