- type: entity
  abstract: true
  parent:
    - BaseMob
    - MobDamageable
    - MobAtmosExposed
    - MobCombat
    - MobBloodstream
    - MobFlammable
  id: MobXenoBase
  components:
    - type: Xeno
    - type: XenoEvolutions
    - type: XenoTier
    - type: Actions
    - type: UserInterface
      interfaces:
        - key: enum.XenoEvolutionUiKey.Key
          type: XenoEvolutionBoundUserInterface
    - type: ShowXenoAgeIcons
    - type: Insulated
    - type: CombatMode
      combatToggleAction: ActionXenoCombatModeToggle
    - type: InputMover
    - type: MobMover
    - type: Tool
      speed: 1.5
      qualities:
        - Prying
      useSound:
        path: /Audio/Items/crowbar.ogg
    - type: Reactive
      groups:
        Flammable: [ Touch ]
        Extinguish: [ Touch ]
    - type: NpcFactionMember
      factions:
      - Xeno
    - type: Hands
    - type: Body
    - type: Climbing
    - type: Flashable
    - type: NameIdentifier
      group: GenericNumber
    - type: MobState
      allowedStates:
      - Alive
      - Dead
    - type: Stamina
      critThreshold: 200
    - type: DamageStateVisuals
      rotate: true
      states:
        Alive:
          Base: running
        Critical:
          Base: crit
        Dead:
          Base: dead
    - type: Puller
      needsHands: false
      walkModifier: 0.4
      sprintModifier: 0.4
    - type: TypingIndicator
      proto: alien
    - type: Temperature
      heatDamageThreshold: 360
      coldDamageThreshold: -150
      currentTemperature: 310.15
    - type: Eye
      drawFov: false
    - type: Sprite
      drawdepth: Mobs
      sprite: Mobs/Aliens/Xenos/queen.rsi
      layers:
      - map: ["enum.DamageStateVisualLayers.Base"]
        state: running
    - type: MobThresholds
      thresholds:
        0: Alive
        300: Dead
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 9
    - type: MeleeWeapon
      altDisarm: false
      hidden: true
      angle: 30
      soundHit:
        collection: AlienClaw
      damage:
        groups:
          Brute: 25
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.75
          density: 550
          mask:
          - MobMask
          layer:
          - MobLayer
    - type: Tag
      tags:
        - CannotSuicide
        - DoorBumpOpener
        - FootstepSound
        - DoorBumpOpener
    - type: NoSlip
    - type: Perishable # Ummmm the acid kills a lot of the bacteria or something
      molsPerSecondPerUnitMass: 0.0005
    - type: Speech
      speechVerb: LargeMob
    - type: StatusEffects
      allowed:
      - SlowedDown
      - Stutter
      - Electrocution
      - ForcedSleep
      - TemporaryBlindness
      - Pacified
    - type: Buckle
    - type: StandingState
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 5
    - type: IntrinsicRadioReceiver
    - type: IntrinsicRadioTransmitter
      channels:
      - Hivemind
    - type: ActiveRadio
      channels:
      - Hivemind
    - type: UnpoweredFlashlight
      toggleAction: ActionToggleLightXeno
    - type: PointLight
      enabled: false
      radius: 6
      softness: 5
      color: "#FF33FF"
      autoRot: true
    - type: Prying
      speedModifier: 2.75
      pryPowered: true
      force: true
    - type: Bloodstream
      bloodlossThreshold: 0
      bloodRefreshAmount: 150
      bloodReagent: FluorosulfuricAcid 
    - type: LizardAccent

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT0
  components:
    - type: XenoTier
      tier: 0
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 2
    - type: MovementSpeedModifier
      baseWalkSpeed: 3
      baseSprintSpeed: 6
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.45
          density: 550
          mask:
          - MobMask
          layer:
          - MobLayer

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT1
  components:
    - type: XenoTier
      tier: 1
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 4
      - id: ResearchMaterial
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 3
      baseSprintSpeed: 6
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.45
          density: 550
          mask:
          - MobMask
          layer:
          - MobLayer

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT2
  components:
    - type: XenoTier
      tier: 2
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 8
      - id: ResearchMaterial3000
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 2.5
      baseSprintSpeed: 5

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT3
  components:
    - type: XenoTier
      tier: 3
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 12
      - id: ResearchMaterial5000
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 2.5
      baseSprintSpeed: 5


- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT4
  components:
    - type: XenoTier
      tier: 4
    - type: Butcherable
      butcheringType: Knife
      spawned:
      - id: FoodMeatXeno
        amount: 20
      - id: ResearchMaterial10000
        amount: 1
    - type: MovementSpeedModifier
      baseWalkSpeed: 2.5
      baseSprintSpeed: 5