- type: entity
  name: Queen
  parent: MobXeno
  id: MobXenoBase
  abstarct: true
  components:
    - type: Xeno
    - type: Sprite
      drawdepth: Mobs
      sprite: Mobs/Aliens/Xenos/queen.rsi
      offset: 0,0.4
      layers:
      - map: ["enum.DamageStateVisualLayers.Base"]
        state: running
    - type: MobThresholds
      thresholds:
        0: Alive
        300: Dead
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 9
    - type: MeleeWeapon
      hidden: true
      damage:
        groups:
          Brute: 25
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.45
          density: 15500
          mask:
          - MobMask
          layer:
          - MobLayer
