- type: entity
  abstract: true
  parent:
    - BaseMob
    - MobDamageable
    - MobAtmosExposed
    - MobCombat
    - MobBloodstream
    - MobFlammable
  id: MobXenoBase
  components:
    - type: Xeno
    - type: Insulated
    - type: CombatMode
    - type: InputMover
    - type: MobMover
    - type: Tool
      speed: 1.5
      qualities:
        - Prying
      useSound:
        path: /Audio/Items/crowbar.ogg
    - type: Reactive
      groups:
        Flammable: [Touch]
        Extinguish: [Touch]
    - type: NpcFactionMember
      factions:
      - Xeno
    - type: Hands
    - type: Body
      prototype: Animal
    - type: Climbing
    - type: Flashable
    - type: NameIdentifier
      group: GenericNumber
    - type: MobState
      allowedStates:
      - Alive
      - Dead
    - type: Stamina
      critThreshold: 200
    - type: Bloodstream
      bloodReagent: FluorosulfuricAcid
    - type: DamageStateVisuals
      rotate: true
      states:
        Alive:
          Base: running
        Critical:
          Base: crit
        Dead:
          Base: dead
    - type: Puller
      needsHands: false
    - type: Butcherable
      butcheringType: Spike
      spawned:
      - id: FoodMeatXeno
        amount: 5
    - type: TypingIndicator
      proto: alien
    - type: Temperature
      heatDamageThreshold: 360
      coldDamageThreshold: -150
      currentTemperature: 310.15
    - type: Sprite
      drawdepth: Mobs
      sprite: Mobs/Aliens/Xenos/queen.rsi
      offset: 0,0.4
      layers:
      - map: ["enum.DamageStateVisualLayers.Base"]
        state: running
    - type: MobThresholds
      thresholds:
        0: Alive
        300: Dead
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 9
    - type: MeleeWeapon
      altDisarm: false
      hidden: true
      angle: 30
      soundHit:
        collection: AlienClaw
      damage:
        groups:
          Brute: 25
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.45
          density: 15500
          mask:
          - MobMask
          layer:
          - MobLayer
    - type: Tag
      tags:
        - CannotSuicide
        - DoorBumpOpener
        - FootstepSound
        - DoorBumpOpener
    - type: NoSlip
    - type: Perishable # Ummmm the acid kills a lot of the bacteria or something
      molsPerSecondPerUnitMass: 0.0005
    - type: Speech
      speechVerb: LargeMob
    - type: StatusEffects
      allowed:
      - SlowedDown
      - Stutter
      - Electrocution
      - ForcedSleep
      - TemporaryBlindness
      - Pacified
    - type: Buckle
    - type: StandingState

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT1
  components:
    - type: MovementSpeedModifier
      baseWalkSpeed: 6
      baseSprintSpeed: 12

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT2
  components:
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 10

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT3
  components:
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 8

- type: entity
  abstract: true
  parent: MobXenoBase
  id: MobXenoBaseT4
  components:
    - type: MovementSpeedModifier
      baseWalkSpeed: 5
      baseSprintSpeed: 8