- type: job
  id: BravoCommander
  name: job-name-bravo-commander
  description: job-description-bravocommander
  playTimeTracker: JobBravoCommander
  requirements:
    - !type:DepartmentTimeRequirement
      department: SpecialistsGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: MedicsGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: EngineersGarrison
      time: 0
    - !type:DepartmentTimeRequirement
      department: MarinesGarrison
      time: 0
  startingGear: BravoCommanderGear
  icon: "JobIconBravoCommander"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - SquadBravo
    - SquadLeader
    - Command

- type: startingGear
  id: BravoCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitbravo_leader
    id: BCommanderIDCard
    ears: ClothingHeadsetMarineBravoLeader
