- type: job
  id: BravoCommander
  name: job-name-bravo-commander
  description: job-description-bravocommander
  playTimeTracker: JobBravoCommander
  requirements:
    - !type:DepartmentTimeRequirement
      department: EngineersGarrison
      time: 32400 # 3 hrs
    - !type:DepartmentTimeRequirement
      department: SpecialistsGarrison
      time: 32400 # 3 hrs
    - !type:DepartmentTimeRequirement
      department: MedicsGarrison
      time: 32400 # 3 hrs
  startingGear: BravoCommanderGear
  icon: "JobIconBravoCommander"
  supervisors: job-supervisors-field-commander
  canBeAntag: false
  access:
    - SquadBravo
    - SquadLeader
    - SquadSpecialist
    - Engineering
    - Command
    - Medical

- type: startingGear
  id: BravoCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitbravo_leader
    id: BCommanderIDCard
    ears: ClothingHeadsetMarineBravoLeader
