- type: job
  id: BravoMedic
  name: job-name-bravo-medic
  description: job-description-bravomedic
  playTimeTracker: JobBravoMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 36000 # 10 hrs
  startingGear: BravoMedicGear
  icon: "JobIconBravoMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadBravoMedic

- type: startingGear
  id: BravoMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitbravo_med
    id: BMedicIDCard
    ears: ClothingHeadsetMarineBravo
