- type: job
  id: Quinn
  name: job-name-quinn
  description: job-description-quinn
  playTimeTracker: JobQuinn
  requirements:
    - !type:RoleTimeRequirement
      role: JobKseno
      time: 72000 # 20 hrs
  canBeAntag: false
  icon: "JobIconQuinn"
  supervisors: job-supervisors-quinn
  jobEntity: MobQueenXeno
