- type: job
  id: PilotMech
  name: job-name-pilotmech
  description: job-description-pilotmech
  playTimeTracker: JobPilotMech
  startingGear: MechPilotGear
  icon: "JobIconPilotMech"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  access:
    - Command
    - Pilot
    - PilotMech
    - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: PilotMech

- type: startingGear
  id: MechPilotGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMechPilot
    back: ClothingBackpackMarine
    shoes: ClothingShoesBootsCombat
    id: PilotMechIDCard
