- type: job
  id: PilotRaptor
  name: job-name-pilotraptor
  description: job-description-pilotnormandy
  playTimeTracker: JobPilotNormandy
  startingGear: PilotOfficerGear
  icon: "JobIconPilotOfficer"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  access:
    - Command
    - Pilot
    - PilotRaptor
    - Maintenance

- type: startingGear
  id: PilotOfficerGear
  equipment:
    head: ClothingHeadHelmetMarine
    jumpsuit: ClothingUniformJumpsuitMarine
    back: ClothingBackpackMarine
    shoes: ClothingShoesBootsCombat
    eyes: ClothingEyesGlassesRPG
    id: PilotRaptorIDCard
    ears: ClothingHeadsetPilotShattle
