- type: job
  id: AlfaEngineer
  name: job-name-alfa-engineer
  description: job-description-alfaengineer
  playTimeTracker: JobAlfaEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 10800 # 3 hrs
  startingGear: AlfaEngineerGear
  icon: "JobIconAlfaEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadAlpha
    - Maintenance
    - Engineering
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: AlfaEngineer

- type: startingGear
  id: AlfaEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_eng
    id: AEngineerIDCard
    ears: ClothingHeadsetMarineAlfa
    pocket1: EmergencyMedipen
