- type: job
  id: PilotMech
  name: job-name-pilotmech
  description: job-description-pilotmech
  playTimeTracker: JobPilotMech
  startingGear: MechPilotGear
  icon: "JobIconPilotMech"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
  - !type:RoleTimeRequirement
      role: JobPilotNormandy
      time: 18000 # 5 hrs
  access:
    - Command
    - Pilot
    - PilotMech
    - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: PilotMech

- type: startingGear
  id: MechPilotGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMechPilot
    back: ClothingBackpackMarine
    shoes: ClothingShoesBootsCombat
    id: PilotMechIDCard
    ears: ClothingHeadsetPilotShattle
    pocket1: EmergencyMedipen
