- type: job
  id: PilotRaptor
  name: job-name-pilotraptor
  description: job-description-pilotraptor
  playTimeTracker: JobPilotRaptor
  startingGear: PilotOfficerGear
  icon: "JobIconPilotOfficer"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
  - !type:RoleTimeRequirement
      role: JobPilotNormandy
      time: 18000 # 5 hrs
  access:
    - Command
    - Pilot
    - PilotNormandy
    - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: PilotRaptor

- type: startingGear
  id: PilotOfficerGear
  equipment:
    head: ClothingHeadHelmetMarine
    jumpsuit: ClothingUniformJumpsuitMarine
    back: ClothingBackpackMarine
    shoes: ClothingShoesBootsCombat
    eyes: ClothingEyesGlassesRPG
    id: PilotRaptorIDCard
    ears: ClothingHeadsetPilotShattle
    pocket1: EmergencyMedipen
