- type: job
  id: SupplyOfficer
  name: job-name-supplyofficer
  description: job-description-supplyofficer
  playTimeTracker: JobSupplyOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: SupplyOfficerGear
  icon: "JobIconSupplyOfficer"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  access:
    - Cargo
    - Quartermaster
    - Command

- type: startingGear
  id: SupplyOfficerGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
    id: SupplyOfficerIDCard
