- type: jobRank
  id: MilitaryMainMedic
  job: MilitaryMainMedic
  requirements:
  - !type:JobRankTimeRequirement
    role: JobMilitaryMainMedic
    time: 0
    icon: JobRankChiefHealthOfficer
  - !type:JobRankTimeRequirement
    role: JobMilitaryMainMedic
    time: 180000 # 50 hours
    icon: JobRankCMO

- type: jobRank
  id: MilitaryMedic
  job: MilitaryMedic
  requirements:
  - !type:JobRankTimeRequirement
    role: JobMilitaryMedic
    time: 0
    icon: JobRankMedicalResident
  - !type:JobRankTimeRequirement
    role: JobMilitaryMedic
    time: 180000 # 50 hours
    icon: JobRankMedicalDoctor
