[game]
hostname = "🛰️ Corvax — CM 👾 [ЗБТ]"
desc = "CM первый русскоязычный проект в Space Station 14.\nНа CMе средние требования к RP."
maxplayers = 120
soft_max_players = 105
map_rotation = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"
