[game]
hostname = "🛰️ Corvax — Colonial Marines 🦂 [ЗБТ]"
desc = "Colonial Marines первый русскоязычный проект в Space Station 14.\nНа Colonial Marines средние требования к RP."
maxplayers = 120
soft_max_players = 100
map_rotation = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"
