- type: job
  id: MilitaryPoliceman
  name: job-name-militarypoliceman
  description: job-description-militarypoliceman
  playTimeTracker: JobMilitaryPoliceman
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 18000 # 5 hrs
  startingGear: MilitaryPolicemanGear
  icon: "JobIconMilitaryPoliceman"
  supervisors: job-supervisors-police-officer
  canBeAntag: false
  accessGroups:
    - MilitaryPoliceman
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: MilitaryPoliceman

- type: startingGear
  id: MilitaryPolicemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryPolice
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterVestArmorSec # Corvax-Resprite
    id: PolicemanIDCard
    ears: ClothingHeadsetSecurity
