- type: job
  id: FieldCommander
  name: job-name-fieldcommander
  description: job-description-fieldcommander
  playTimeTracker: JobFieldCommander
  requirements:
  - !type:DepartmentTimeRequirement
    department: CommandersGarrisons
    time: 36000 # 10 hours
  startingGear: FieldCommanderGear
  icon: "JobIconFieldCommander"
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  accessGroups:
    - HeadOperations
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: FieldCommander

- type: startingGear
  id: FieldCommanderGear
  equipment:
    head: ClothingHeadHatBeretFieldCommander
    outerClothing: ClothingOuterArmorFieldCommander
    gloves: ClothingHandsGlovesMarine
    jumpsuit: ClothingUniformJumpsuitFieldCommander
    eyes: ClothingEyesGlassesRPG
    id: FieldCommanderIDCard
    ears: ClothingHeadsetMarineCommands
    belt: ClothingBeltSecurityFilled
    shoes: ClothingShoesBootsMarine
    pocket1: EmergencyMedipen
    pocket2: ClothingMaskGasFieldCommander
