- type: job
  id: StaffOfficer
  name: job-name-staffofficer
  description: job-description-staffofficer
  playTimeTracker: JobStaffOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryPoliceOfficer
      time: 3600 # 1 hrs
    - !type:RoleTimeRequirement
      role: JobSupplyOfficer
      time: 3600 # 1 hrs
    - !type:RoleTimeRequirement
      role: JobFieldCommander
      time: 3600 # 1 hrs
    - !type:DepartmentTimeRequirement
      department: CommandersGarrisons
      time: 3600 # 1 hrs
  startingGear: StaffOfficerGear
  icon: "JobIconStaffOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - HeadOperations
  special:
  - !type:AddComponentSpecial
    components:
      - type: JobRank
        job: StaffOfficer

- type: startingGear
  id: StaffOfficerGear
  equipment:
    neck: ClothingNeckHeadphones
    gloves: ClothingHandsGlovesMarine
    jumpsuit: ClothingUniformJumpsuitStaffOfficer
    eyes: ClothingEyesGlassesRPG
    id: StaffOfficerIDCard
    ears: ClothingHeadsetMarineHeadOperation
    belt: ClothingBeltAssault
    shoes: ClothingShoesCentcomBlack
    pocket1: EmergencyMedipen
