- type: entity
  id: ActionXenoBuildWall
  name: action-xeno-build-wall
  description: desc-action-drone-build-wall
  noSpawn: true
  components:
  - type: WorldTargetAction
    range: 1.4
    useDelay: 0
    sound: !type:SoundCollectionSpecifier
      collection: XenoBreath
      params:
        volume: 0.5
    icon:
      sprite: Actions/xeno.rsi
      state: build_wall
    itemIconStyle: NoItem
    event: !type:XenoBuildWallEvent
    checkCanAccess: false