- type: entity
  id: ActionXenoBuildWall
  name: action-xeno-build-wall
  description: desc-action-drone-build-wall
  noSpawn: true
  components:
    - type: WorldTargetAction
      range: 2
      useDelay: 0
      sound: !type:SoundPathSpecifier
        path: /Audio/Effects/alien_roar1.ogg
      icon:
        sprite: Actions/xeno.rsi
        state: build_wall
      itemIconStyle: NoItem
      event: !type:XenoBuildWallEvent
      checkCanAccess: false