- type: job
  id: AlfaCommander
  name: job-name-alfa-commander
  description: job-description-alfacommander
  playTimeTracker: JobAlfaCommander
  requirements:
    - !type:RoleTimeRequirement
      role: JobShipsEngineer
      time: 36000 # 10 hrs
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 108000 # 30 hrs
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 36000 # 10 hrs
  startingGear: AlfaCommanderGear
  icon: "JobIconAlfaCommander"
  supervisors: job-supervisors-field-commander
  canBeAntag: false
  access:
    - SquadAlpha
    - SquadLeader
    - SquadSpecialist
    - Engineering
    - Command
    - Medical

- type: startingGear
  id: AlfaCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_leader
    id: ACommanderIDCard
    ears: ClothingHeadsetMarineAlfaLeader
