- type: job
  id: AlfaMarine
  name: job-name-alfa-marine
  description: job-description-alfamarine
  playTimeTracker: JobAlfaMarine
  startingGear: AlfaMarineGear
  icon: "JobIconAlfaMarine"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - SquadAlpha

- type: startingGear
  id: AlfaMarineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_mar
    id: ARiflemanIDCard
    ears: ClothingHeadsetMarineAlfa
