- type: job
  id: AlfaEngineer
  name: job-name-alfa-engineer
  description: job-description-alfaengineer
  playTimeTracker: JobAlfaEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: AlfaEngineerGear
  icon: "JobIconAlfaEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadAlpha
    - Engineering

- type: startingGear
  id: AlfaEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_eng
    id: AEngineerIDCard
    ears: ClothingHeadsetMarineAlfa
