- type: job
  id: AlfaMedic
  name: job-name-alfa-medic
  description: job-description-alfamedic
  playTimeTracker: JobAlfaMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 36000 # 10 hrs
  startingGear: AlfaMedicGear
  icon: "JobIconAlfaMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadAlphaMedic

- type: startingGear
  id: AlfaMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_med
    id: AMedicIDCard
    ears: ClothingHeadsetMarineAlfa
